version: 'demo'

batch_size: 50
epochs: 50
parameter_save_root: 'parameters'
check_point: False
seed: 42

model:
  lr: 0.001
  backbone: "resnet18"
  in_channels: 20
  out_channels: 3
  drop_rate: 0.2


