version: 'demo'

dataloader:
  size: 1
  num_workers: 0

run:
  batch_size: 50
  epochs: 50
  check_point: False
  seed: 42

model:
  lr: 0.001
  backbone: "resnet18"
  in_channels: 20
  out_channels: 3
  drop_rate: 0.2
  parameter_dir: '/Users/wanghaolin/GitHub/PokeLab/Method/parameters'


